/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.CAppointment;
import Model.DBConnection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import java.awt.Font;

import java.sql.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author nimes
 */
public class VDashboard extends javax.swing.JFrame {

    /**
     * Creates new form VDashboard
     */
    public VDashboard() {
        initComponents();
    }
    
    private DefaultTableModel tableModel;
    private ResultSet rst;
    
    private void populateTableWithData() {
        
    // Create a font with the desired size
    Font tableFont = new Font("Segoe UI", Font.PLAIN, 36); // Change the font and size as needed

    // Create a cell renderer with the new font
    DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
    cellRenderer.setFont(tableFont);

    // Apply the cell renderer to all columns
    for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++) {
        tbl_appoint1.getColumnModel().getColumn(columnIndex).setCellRenderer(cellRenderer);
    }
     CAppoinment c1 = new CAppoinment();
    rst = c1.getSubjectInfo();

    
    try {
    // Clear any existing data
    tableModel.setRowCount(0);
    
    
    
    // Populate the table model with data from the result set
    while (rst.next()) {
        String SubjectName = rst.getString("subName");
        
        // Add the data to the table model
        Object[] rowData = {SubjectName};
        tableModel.addRow(rowData);
    }
} catch (SQLException e) {
    e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pastapp = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_appoint1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_report = new javax.swing.JButton();
        btn_addroom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        tbl_pastapp.setBackground(new java.awt.Color(204, 204, 204));
        tbl_pastapp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Name", "Appoinment Date", "Book Start Time", "Book end Time", "Purpose", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_pastapp);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(77, 332, 620, 150);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Appontments");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 89, 90, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Past Appointments");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 298, 110, 16);

        tbl_appoint1.setBackground(new java.awt.Color(204, 204, 204));
        tbl_appoint1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Room Name", "Appoinment Date", "Book Start Time", "Book End Time", "Purpose", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_appoint1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(80, 133, 620, 150);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 600));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        btn_report.setBackground(new java.awt.Color(153, 153, 153));
        btn_report.setText("Report");
        btn_report.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportActionPerformed(evt);
            }
        });
        jPanel2.add(btn_report);
        btn_report.setBounds(620, 470, 100, 40);

        btn_addroom.setBackground(new java.awt.Color(153, 153, 153));
        btn_addroom.setText("Add Studio Room");
        btn_addroom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_addroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addroomActionPerformed(evt);
            }
        });
        jPanel2.add(btn_addroom);
        btn_addroom.setBounds(570, 50, 113, 41);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 30, 740, 510);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Admin Dashboard");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(300, 0, 170, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 780, 560);

        setSize(new java.awt.Dimension(795, 570));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addroomActionPerformed
        VAddRoom v1 = new VAddRoom();
        v1.setVisible(true);
    }//GEN-LAST:event_btn_addroomActionPerformed

    private void btn_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportActionPerformed
        try
        {
            DBConnection.connectDB();
            JasperDesign jasDesign = JRXmlLoader.load("C:\\Users\\nimes\\Documents\\NetBeansProjects\\EADFinal\\src\\View\\report1.jrxml");
            JRDesignQuery desquery = new JRDesignQuery();   
            String sqlquery = "SELECT r.roomname, r.roomPrice, COUNT(a.appointment_id) AS numAppointments, SUM(a.price) AS totalIncome FROM rooms r LEFT JOIN appointment a ON r.roomname = a.roomname GROUP BY r.roomname, r.roomPrice ORDER BY totalIncome DESC;";
            desquery.setText(sqlquery);
            JasperReport jasreport = JasperCompileManager.compileReport(jasDesign);
            JasperPrint jasprint = JasperFillManager.fillReport(jasreport,null,DBConnection.connectDB());
            JasperViewer.viewReport(jasprint,false);
        
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_reportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addroom;
    private javax.swing.JButton btn_report;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_appoint1;
    private javax.swing.JTable tbl_pastapp;
    // End of variables declaration//GEN-END:variables

    private static class CAppoinment {

        public CAppoinment() {
        }

        private ResultSet getSubjectInfo() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
